// Lista de ativos brasileiros mais comuns
// Atualizada em Janeiro/2025

export const ativosBrasileiros = {
  // AÇÕES - Empresas listadas na B3
  'PETR3': 'Petrobras ON',
  'PETR4': 'Petrobras PN',
  'VALE3': 'Vale ON',
  'ITUB3': 'Itaú Unibanco ON',
  'ITUB4': 'Itaú Unibanco PN',
  'BBDC3': 'Bradesco ON',
  'BBDC4': 'Bradesco PN',
  'ABEV3': 'Ambev ON',
  'B3SA3': 'B3 ON',
  'BBAS3': 'Banco do Brasil ON',
  'WEGE3': 'WEG ON',
  'RENT3': 'Localiza ON',
  'RAIL3': 'Rumo ON',
  'SUZB3': 'Suzano ON',
  'JBSS3': 'JBS ON',
  'MGLU3': 'Magazine Luiza ON',
  'LREN3': 'Lojas Renner ON',
  'HAPV3': 'Hapvida ON',
  'RADL3': 'Raia Drogasil ON',
  'PRIO3': 'PRIO ON',
  'CSAN3': 'Cosan ON',
  'GGBR4': 'Gerdau PN',
  'CSNA3': 'CSN ON',
  'USIM5': 'Usiminas PNA',
  'EMBR3': 'Embraer ON',
  'CCRO3': 'CCR ON',
  'CPLE6': 'Copel PNB',
  'CMIG4': 'Cemig PN',
  'ELET3': 'Eletrobras ON',
  'ELET6': 'Eletrobras PNB',
  'TAEE11': 'Taesa UNT',
  'EGIE3': 'Engie Brasil ON',
  'EQTL3': 'Equatorial ON',
  'SBSP3': 'Sabesp ON',
  'CIEL3': 'Cielo ON',
  'PCAR3': 'GPA ON',
  'BRFS3': 'BRF ON',
  'BEEF3': 'Minerva ON',
  'MRFG3': 'Marfrig ON',
  'PETZ3': 'Petz ON',
  'ASAI3': 'Assaí ON',
  'CRFB3': 'Carrefour Brasil ON',
  'VBBR3': 'Vibra Energia ON',
  'UGPA3': 'Ultrapar ON',
  'KLBN11': 'Klabin UNT',
  'VIVT3': 'Telefônica Brasil ON',
  'TOTS3': 'TOTVS ON',
  'LWSA3': 'Locaweb ON',
  'POSI3': 'Positivo ON',
  'POMO4': 'Marcopolo PN',
  'RAIZ4': 'Raízen PN',
  'RECV3': 'PetroReconcavo ON',
  'RRRP3': '3R Petroleum ON',
  'SOMA3': 'Grupo Soma ON',
  'YDUQ3': 'Yduqs ON',
  'COGN3': 'Cogna ON',
  'ANIM3': 'Ânima ON',
  'SEER3': 'Ser Educacional ON',
  'MULT3': 'Multiplan ON',
  'BRML3': 'BR Malls ON',
  'IGTI11': 'Iguatemi UNT',
  'ALPA4': 'Alpargatas PN',
  'GUAR3': 'Guararapes ON',
  'ARZZ3': 'Arezzo ON',
  'SLCE3': 'SLC Agrícola ON',
  'SMTO3': 'São Martinho ON',
  'MEAL3': 'IMC ON',
  'FLRY3': 'Fleury ON',
  'RDOR3': 'Rede D\'Or ON',
  'HYPE3': 'Hypera ON',
  'QUAL3': 'Qualicorp ON',
  'ODPV3': 'Odontoprev ON',
  'SAPR11': 'Sanepar UNT',
  'TIMS3': 'TIM ON',
  'DXCO3': 'Dexco ON',
  'EVEN3': 'Even ON',
  'CYRE3': 'Cyrela ON',
  'MRVE3': 'MRV ON',
  'EZTC3': 'EZ Tec ON',
  'JHSF3': 'JHSF ON',
  'DIRR3': 'Direcional ON',
  'ALSO3': 'Aliansce Sonae ON',
  'GOLL4': 'Gol PN',
  'AZUL4': 'Azul PN',
  'IRBR3': 'IRB Brasil ON',
  'CVCB3': 'CVC ON',
  'GOAU4': 'Gerdau Metalúrgica PN',
  'BRKM5': 'Braskem PNA',
  'UNIP6': 'Unipar PNB',
  'BRDT3': 'Petrobras Distribuidora ON',

  // FIIs - Fundos Imobiliários
  'HGLG11': 'CSHG Logística FII',
  'MXRF11': 'Maxi Renda FII',
  'XPML11': 'XP Malls FII',
  'VISC11': 'Vinci Shopping Centers FII',
  'BTLG11': 'BTG Pactual Logística FII',
  'KNCR11': 'Kinea Renda Imobiliária FII',
  'KNRI11': 'Kinea Rendimentos Imobiliários FII',
  'LVBI11': 'VBI Logístico FII',
  'HGRU11': 'CSHG Renda Urbana FII',
  'HGRE11': 'CSHG Real Estate FII',
  'RECT11': 'REC Recebíveis Imobiliários FII',
  'BCFF11': 'BTG Pactual Fundo de Fundos FII',
  'MALL11': 'Malls Brasil FII',
  'IRDM11': 'Iridium Recebíveis Imobiliários FII',
  'RBRR11': 'RBR Rendimento FII',
  'TGAR11': 'TG Ativo Real FII',
  'VGIR11': 'Valora RE III FII',
  'XPLG11': 'XP Log FII',
  'JSRE11': 'JS Real Estate FII',
  'TRXF11': 'TRX Real Estate FII',
  'CPTS11': 'Capitânia Securities II FII',
  'VILG11': 'Vinci Logística FII',
  'ALZR11': 'Alianza Trust Renda Imobiliária FII',
  'PVBI11': 'VBI Prime Properties FII',
  'RBVA11': 'Rio Bravo Renda Varejo FII',
  'HGBS11': 'CSHG Brasil Shopping FII',
  'VCJR11': 'Vinci Core Jardins FII',
  'HSML11': 'HSI Malls FII',
  'RBRP11': 'RBR Properties FII',
  'BBPO11': 'BB Progressivo II FII',
  'BBFI11B': 'BB Renda de Papéis FII',
  'XPPR11': 'XP Properties FII',
  'MCCI11': 'Maua Capital Recebíveis Imobiliários FII',
  'RBRY11': 'RBR Alpha FII',
  'KNSC11': 'Kinea Securities FII',
  'VINO11': 'Vinci Offices FII',
  'SARE11': 'Santander Renda de Aluguéis FII',
  'RBRF11': 'RBR High Grade FII',
  'XPCI11': 'XP Corporate Macaé FII',
  'VGHF11': 'Valora Hedge Fund FII',

  // ETFs - Fundos de Índice
  'BOVA11': 'iShares Ibovespa Fundo de Índice',
  'IVVB11': 'iShares S&P 500 Fundo de Índice',
  'SMAL11': 'iShares BM&F Bovespa Small Cap Fundo de Índice',
  'PIBB11': 'iShares BM&F Bovespa Brasil 50 Fundo de Índice',
  'DIVO11': 'CSHG Dividendos FI',
  'MATB11': 'iShares BM&F Bovespa Materiais Básicos Fundo de Índice',
  'FIND11': 'iShares BM&F Bovespa Financeiro Fundo de Índice',
  'ISUS11': 'iShares S&P Sustainability Fundo de Índice',
  'HASH11': 'Hashdex NCI Criptoativos FI',
  'WRLD11': 'iShares MSCI World',
  'ESGB11': 'Investo ESG FI',
  'BRAX11': 'EQI Brazil 100 FI',
  'XBOV11': 'XP Ibovespa FI',

  // BDRs - Brazilian Depositary Receipts (Ações Internacionais)
  'AAPL34': 'Apple Inc BDR',
  'MSFT34': 'Microsoft Corporation BDR',
  'GOGL34': 'Alphabet Inc (Google) BDR',
  'AMZO34': 'Amazon.com Inc BDR',
  'TSLA34': 'Tesla Inc BDR',
  'META34': 'Meta Platforms Inc (Facebook) BDR',
  'NFLX34': 'Netflix Inc BDR',
  'NVDC34': 'NVIDIA Corporation BDR',
  'DISB34': 'The Walt Disney Company BDR',
  'COCA34': 'The Coca-Cola Company BDR',
  'P1EP34': 'PepsiCo Inc BDR',
  'MBLY34': 'McDonald\'s Corporation BDR',
  'NIKE34': 'Nike Inc BDR',
  'VISA34': 'Visa Inc BDR',
  'WALM34': 'Walmart Inc BDR',
  'BOAC34': 'The Boeing Company BDR',
}

// Função de busca
export function buscarAtivo(ticker) {
  const tickerUpper = ticker.toUpperCase().trim()
  return ativosBrasileiros[tickerUpper] || null
}

// Função de busca com sugestões (para autocomplete futuro)
export function buscarAtivosSimilares(termo, limite = 5) {
  const termoUpper = termo.toUpperCase().trim()
  const resultados = []
  
  for (const [ticker, nome] of Object.entries(ativosBrasileiros)) {
    if (ticker.includes(termoUpper) || nome.toUpperCase().includes(termoUpper)) {
      resultados.push({ ticker, nome })
      if (resultados.length >= limite) break
    }
  }
  
  return resultados
}
